Support for read view
chuangcaleb/obsidian-fountain-editor pull request #41
Opened 2024-08-06 14:00 UTC by NickEastNL

As per the discussion here: https://github.com/chuangcaleb/obsidian-fountain-editor/discussions/33

I _believe_ I've added all important elements of the Fountain spec to render properly in read view. The only elements I've not done are (section) headings, since to me they already appear fine, and the boneyard.

The boneyard is especially complex because without empty lines the block renders as a single paragraph, with the asterisks interpreted as emphasis/italics. With empty lines, the start and end blocks are detected properly, but they all become separate paragraphs. Since I don't use the boneyard element, they are not intended to be rendered anyway, and otherwise the Obsidian "comment" syntax does the same thing, I've chosen not to add it. If you still want to, I can look at it. Alternatively it should be possible to convert syntax when exporting a Fountain document out of Obsidian.

Other than that, the changes should be self-explanatory, so let me know what you think.

2024-08-09 14:04 UTC, chuangcaleb commented
Great work @NickEastNL! Thanks so much for contributing 😍
I've left some review comments.
I think I won't spend too much time and effort on refining Reading View, as it's not in my personal use case at all (and I'm not sure how many people do) but if it's small refactoring efforts, I can contribute there! I may offer some changes to your PR as well! We'll work on this together!

2025-03-31 13:49 UTC, chuangcaleb requested changes

2025-03-31 13:49 UTC, chuangcaleb commented on src/editor/decorations.ts
> +import { editorInfoField } from "obsidian";
hmm formatting diffs. is the `xo` formatter installed on your side?

2025-03-31 13:49 UTC, chuangcaleb commented on src/editor/decorations.ts
> +				if (firstChar === "\\") {
oh, why are we adding this rule? is there a syntax spec for dialogue that starts with `\\`?

2025-03-31 13:49 UTC, chuangcaleb commented on src/markdownPostProcessor.ts
i'll review this again once the other reviews are addressed. I was also thinking to maybe implement it more similar to how the old [obsidian-fountain](https://publish.obsidian.md/hub/02+-+Community+Expansions/02.05+All+Community+Expansions/Plugins/obsidian-fountain) (now removed) plugin used to handle it. 

iirc they used [mattdaly/Fountain.js: A JavaScript parser for the screenplay format Fountain](https://github.com/mattdaly/Fountain.js/) and people were happy with how that plugin did Fountain formatting in Reading Mode. Seems a bit sleeker than us manually implementing formatting rules, prone to mistakes. Was forced to do it for Live Preview mode because there seemed to be no other way to hook into the editor. Ya so see how

2025-03-31 13:49 UTC, chuangcaleb commented on src/styles/base.css
> +	--fountain--font-family: "Courier Prime", "Courier", monospace;
im adding this directly; small change, not really related to Reading View feature, will implement it separately!

2025-03-31 13:49 UTC, chuangcaleb commented on src/styles/base.css
> +	--fountain-character-left: calc(var(--fountain--character-left-factor) / var(--fountain--line-width-factor) * var(--fountain-final-line-width));
I think the diff here only because of formatting? if so, then should not be in this PR

2025-03-31 16:05 UTC, NickEastNL commented
It appears I incorrectly assumed the PR was associated up to a certain commit on the master branch. I've only made the recent commits to keep my fork in sync with your repository, since I have to use mine if I want to keep using the read view. As a consequence, I did not pay attention to code style and such.

However, in light of some of the changes and the direction you seem to want to go in, I feel it might be better to ignore the PR and implement it how you feel is best. I'm gravitating towards developing my own plugin (or fully fork this one) for my personal needs. For one, it appears now that there are a few stylistic differences. And I don't use PNPM.

I'll try to answer the questions you've posted above, but I think that's as far as I can go at this point.

2025-03-31 16:11 UTC, NickEastNL commented on src/editor/decorations.ts
> +					markDeco(lFrom, lFrom + 1, composeFClass(token));
This is an awful solution to what appears to me an unsolvable problem: to allow for multi-paragraph dialogue blocks. Fountain relies on double spaces on a new line to interpret the next block as continuous dialogue. Obsidian deletes all whitespace, so when rendered there's no way for the markdown processor to know if a paragraph is supposed to be dialogue.

I just chose the backslash as a placeholder character, and of course added it as a decoration in edit view so it's clear that it works.

2025-03-31 16:14 UTC, NickEastNL commented on src/styles/tokens.css
> +	.fountain-lyrics,
I can't be 100% certain anymore, but I believe it was a quick fix (to not alter your code too much) as by default in Obsidian there's a difference between the styling used for the CodeMirror editor and the rendered HTML, and I deliberately maintained that.

2025-03-31 16:18 UTC, NickEastNL commented on src/styles/tokens.css
> +		margin-block-end: 0;
I'm not 100% sure anymore, but it could've been a placeholder for extra blocks that I felt can be rendered from the Fountain syntax (like a CSS reset). I merely used the two separate lines since Obsidian uses them and I prefer being consistent when resetting or changing original styles. But that's my code style (and I also often break it anyway).

2025-03-31 16:23 UTC, NickEastNL commented on .github/workflows/release.yml
This is the workflow I use for my plugins, taken from other plugins. I don't know exactly what the practical differences are between mine and your original one. I only changed it because I was planning on diverging my fork from yours and felt it was easier to use what I'm used to rather than figure out what the original one was doing.

And as I mention below, I did not anticipate the PR to pick up those commits. You can ignore it, but in general I think it just does the same thing: building the plugin and making it ready for release. The difference I think is that this workflow runs when posting a new release, and adds the artifacts to it.

2025-03-31 16:24 UTC, NickEastNL commented on src/editor/decorations.ts
> +				if (firstChar === "\\") {
Same as above, to allow for multi-paragraph dialogue blocks, since Obsidian markdown removes whitespace when rendering.

2025-03-31 16:30 UTC, NickEastNL commented on src/markdownPostProcessor.ts
I have no idea how that plugin worked, though I believe I tried it? If I'm correct, it worked by using a codeblock to type Fountain, which was then processed by Fountain.js to render HTML, which was then output to the note. Codeblock processors receive the raw text from inside the block, and can output HTML that replaces the block.

That won't work in this case, as your plugin modifies the editor. It doesn't look like we can access the raw note text directly and override Obsidian's renderer to render with Fountain instead of Markdown. All we can do is process the _final rendered_ HTML (which IMO is quite stupid, given the API calls it "Markdown" Post Processor, yet we're not processing the Markdown).

That is also why I had to add the backslash token, since the final HTML loses the double spaces. In addition to a couple other workarounds to query the right HTML elements.

2025-04-02 10:50 UTC, chuangcaleb commented
Hey @NickEastNL! I really appreciate your engagement and actually using this project!! In case that wasn't clear haha. I love that you are making the plugin your own and tweaking it to fit you exactly.

I did formal code reviews, treating it like maintaining a codebase like my day job like my salary depends on it haha. It's also on me, I'm working on providing better contributing guidelines and explaining standards.

I do want to develop this plugin more, but the end goal is always serving the community. Yeah feel free to fork and tune, even better to develop an alternative! Let me know if /I could/you would like me to/ point users to your project if they urgently need features like Reading Mode?

Thanks again for your long and detailed response also. This is my first and only open-source project, I've recently learnt how long it takes to pen replies... I'd like to keep conversation open and see how we can help each other!

2025-04-02 10:53 UTC, chuangcaleb commented on src/markdownPostProcessor.ts
RIGHT they used a codeblock processor. I remember now. Everything is so much simpler in code blocks... Thanks for bringing this up and potentially saving me from chasing a wrong rabbit hole...

Yeah I'll try to take notes from other like plugins that add formatting to Reading Mode in the document body, not the codeblock

2025-04-03 01:15 UTC, closed without merging

2025-04-03 01:15 UTC, chuangcaleb commented
So cool, thanks for this clear channel of communication! yeah, public maintenance is a chore. yeah, would be cool to just look at yours for reference to learn from! This was super beneficial!